name: Cypress Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: "7.0"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          MONGO_URI: mongodb://localhost:27017
          PORT: 8811
          CYPRESS_BASE_URL: http://localhost:8811
        with:
          install-command: npm ci
          build: npm run build
          start: npm start
          wait-on: http://localhost:8811
          browser: firefox
